### ISSUE TITLE
needs css

### ISSUE THREAD

**Issue by Akuli** [Akuli/matikkamerkit#1]
something nice and simple, but less ugly than having no css at all

**Comment by dakers2** [comment]
i'd like to try improving the UI. is there anything you're looking for specifically?

**Comment by Akuli** [comment]
@PROTechThor is making some progress in #2

**Comment by DjigoLab** [comment]
Doing some CSS Grid fixes here!

**Comment by Akuli** [comment]
I already got lots of different css pull requests, but I forgot to close this for some reason
